CREATE TABLE public.inizio_fine_strade
(
  id serial primary key,
  strada_id character varying,
  strada_nome character varying,
  da character varying,
  a character varying
);

insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (259,'90003000969','Via Senza Nome 010','Via Senza Nome 012','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (260,'90003000970','Via Senza Nome 011','STRADA S.S. 127/BIS Km 4, Via Senza Nome 012, VIA SENZA NOME 047','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (261,'90003000971','Via Senza Nome 012','Via Senza Nome 010, Via Senza Nome 011, VIA SENZA NOME 047','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (262,'90003000972','Via Senza Nome 013','STRADA S.S. 127/BIS Km 4, VIA SENZA NOME 047','Via Senza Nome 014, Via Senza Nome 015');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (263,'90003000973','Via Senza Nome 014','','Via Senza Nome 013, Via Senza Nome 015, VIA SENZA NOME 022 (DEI LECCI), VIA SENZA NOME 049 (DEGLI ULIVI (DA VIA DEGLI EUCALIPTI A VIA DEI LECCI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (264,'90003000974','Via Senza Nome 015','Via Senza Nome 013, Via Senza Nome 014, Via Senza Nome 016, VIA SENZA NOME 022 (DEI LECCI), VIA SENZA NOME 024 (DELLE VIGNE)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (265,'90003000975','Via Senza Nome 016','','STRADA S.S. 127/BIS Km 4, Via Senza Nome 015, VIA SENZA NOME 022 (DEI LECCI), VIA SENZA NOME 024 (DELLE VIGNE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (489,'90003001260','STRADA STATALE N� 292 NORD','VIALE GIOVANNI XXIII, VIALE DELLA RESISTENZA, VIA SENZA NOME 239','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (69,'90003001262','STRADA CONSORTILE VESSUS EVENGELETZ','','STRADA SENZA NOME 231');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (64,'90003001263','STRADA CONSORTILE SALONDRA','STRADA STATALE N° 292 NORD','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (65,'90003001264','STRADA CONSORTILE S. ANNA POLLINA','VIA SANT''ANNA','STRADA PROVINCIALE N° 105');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (54,'90003001265','STRADA CONSORTILE CALABONA ARGENTIERA','STRADA CONSORTILE S. ANNA POLLINA, STRADA PROVINCIALE N° 105','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (53,'90003001266','STRADA CONSORTILE BRIONIS','STRADA CONSORTILE S. ANNA POLLINA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (227,'90003001269','STRADA PROVINCIALE N� 105','VIALE DELLA RESISTENZA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (58,'90003001270','STRADA CONSORTILE LA PUSSETTA','STRADA CONSORTILE S. ANNA POLLINA','STRADA PROVINCIALE N° 105');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (449,'90003001273','VIA SENZA NOME 234','','VIALE GIOVANNI XXIII');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (450,'90003001275','VIA SENZA NOME 236','STRADA STATALE N° 292 NORD','VIALE GIOVANNI XXIII');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (451,'90003001276','VIA SENZA NOME 237','','VIALE DELLA RESISTENZA, VIA SENZA NOME 238');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (452,'90003001277','VIA SENZA NOME 238','VIALE DELLA RESISTENZA, VIA SENZA NOME 237','VIA SENZA NOME 245');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (453,'90003001278','VIA SENZA NOME 239','STRADA STATALE N° 292 NORD','VIALE GIOVANNI XXIII, VIALE DELLA RESISTENZA TRAV. C');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (454,'90003001279','VIA SENZA NOME 240 (SANDRO PERTINI)','VIALE GIOVANNI XXIII','VIA SENZA NOME 241');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (455,'90003001280','VIA SENZA NOME 241','VIA SENZA NOME 240 (SANDRO PERTINI)','VIA DE GASPERI ALCIDE TRAV. C');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (457,'90003001282','VIA SENZA NOME 243','VIALE DELLA RESISTENZA TRAV. C','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (111,'90003000716','PIAZZALE EL TRO'' (VIA JOSE'' MARIA ESCRIVA)','VIALE DELLA RESISTENZA, LUNGOMARE VALENCIA, VIA SENZA NOME 134 (TRAVERSA VIA ELTRO'')','VIA SENZA NOME 242 (COMUNEMENTE NOTO P. BALAGUER)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (282,'90003000994','VIA SENZA NOME 034','','VIA STRADA STATALE 127BIS - PORTO CONTE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (319,'90003001053','VIA SENZA NOME 077','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (320,'90003001054','VIA SENZA NOME 078','','VIA SENZA NOME 053, VIA SENZA NOME 054');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (321,'90003001055','VIA SENZA NOME 079','','VIA SENZA NOME 053, VIA SENZA NOME 055');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (221,'90003001010','VIA PORTA A MARE','VIA BANCHINA DOGANA','PIAZZA CIVICA, BASTIONI MAGELLANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (230,'90003001011','VIA P.ZZA PINO PIRAS','LARGO SAN FRANCESCO','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (110,'90003000493','VIA ELEONORA D''ARBOREA','VIA CATALOGNA, VIA GARIBALDI GIUSEPPE, VIA LA MARMORA ALBERTO','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (223,'90003000501','BANCHINA PORTO','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (21,'90003000504','VIA BARCELONETTA','VICOLO ADAMI, VIA ROMA','VIA GIOBERTI, VIA MACHIN AMBROGIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (22,'90003000505','VIA BARCIA','VIA COROS, VIA SANT''ANNA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (24,'90003000506','VIA BERNINI GIOVANNI LORENZO','VIA SATTA SEBASTIANO','VIA CELLINI BENVENUTO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (25,'90003000507','VIA BERTOLOTTI FRANCESCO','VIA OSPEDALE, VIA SANTA BARBARA, PIAZZA SANTA CROCE','BASTIONI MAGELLANO, VIA SANT''ERASMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (26,'90003000508','VIA BRIGATA SASSARI','VIA MAZZINI GIUSEPPE, VIA VITTORIO EMANUELE','VIA SANT''AGOSTINO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (27,'90003000509','VICOLO BURAGNA','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (29,'90003000510','VIA CAGLIARI','VIA CATALOGNA, VIA VITTORIO EMANUELE, VIA SENZA NOME 084 (SCALO TARANTIELLO)','VIALE GIOVANNI XXIII, VIA MAZZINI GIUSEPPE, VIA XX SETTEMBRE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (30,'90003000511','VIA CALABRIA','','VIA LIGURIA, STRADA SENZA NOME 175');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (31,'90003000512','VIA CALA LLONGA','VIA FORADADA, VIA GUIXERA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (32,'90003000514','VIA CANEPA LUIGI','VIA DORE CARMEN, VIA MANZONI ALESSANDRO','VIA DE GASPERI ALCIDE, VIA F.LLI ROSSELLI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (33,'90003000515','VIA CAPPAI MONS. PAOLO','','VIA CANEPA LUIGI, VIA SANT''AGOSTINO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (34,'90003000516','LARGO CAPRERA','LARGO DELLO SPERONE','VIALE SARDEGNA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (35,'90003000517','VIA CARAVAGGIO','VIA GOCEANO, VIA VITTORIO EMANUELE','VIA DIEZ SALVATORE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (36,'90003000518','VIA CARBIA','VIALE DELLA RESISTENZA, VIA VILLAFRANCA DEL PANADES','VIA CARBIA TRAV. B');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (38,'90003000519','VIA CARBIA TRAV. B','','VIA CARBIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (39,'90003000521','VIA CARBONIA','VIA DON MINZONI, VIALE SARDEGNA','VIALE EUROPA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (40,'90003000522','VIA CARDUCCI GIOSUE''','VIA F.LLI KENNEDY, PIAZZA SULIS','VIALE GIOVANNI XXIII, VIA SASSARI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (41,'90003000523','VIA CARLO ALBERTO','PIAZZA CIVICA, VIA ROMA','BASTIONI CRISTOFORO COLOMBO, VIA MINORCA, PIAZZA SULIS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (42,'90003000524','VIA CARRABUFFAS','VIA PORRINO ENNIO, VIA SANT''AGOSTINO, VIA SATTA SEBASTIANO, VIA VALVERDE','STRADA CONSORTILE CARRABUFFAS, VIA SENZA NOME 253');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (43,'90003000525','VIA CASTELSARDO','VIA DON MINZONI, VIA IGLESIAS, VIALE SARDEGNA','VIA DE GIORGIO GIOVANNI, VIA GARIBALDI GIUSEPPE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (44,'90003000526','VIA CATALOGNA','VIA ELEONORA D''ARBOREA, VIA CAGLIARI, VIA LA MARMORA ALBERTO, VIA SENZA NOME 084 (SCALO TARANTIELLO)','VIA DIEZ SALVATORE, VIALE XXIV MAGGIO, VIA VITTORIO VENETO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (45,'90003000527','VIA CATALOGNA VIC.A','','VIA ASFODELO, VIA CATALOGNA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (46,'90003000528','VIA CAVANNA','VIA MAZZINI GIUSEPPE, VIA XX SETTEMBRE','VIA MARCONI GUGLIELMO, VIA MARCONI GUGLIELMO TRAV. A, VIA SANZIO RAFFAELLO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (47,'90003000529','VIA CAVOUR','VIA DON DEROMA, VIA ROMA, VIA SANTA BARBARA','BASTIONI CRISTOFORO COLOMBO, VIA LACCU SIMON, VIA DELLA MISERICORDIA, VICOLO PERETTI, BASTIONI MARCO POLO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (48,'90003000530','VIA CELLINI BENVENUTO','VIA VITTORIO EMANUELE','VIA BERNINI GIOVANNI LORENZO, VIA GOCEANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (119,'90003000531','VIA F.LLI CERVI','VIA PANTELLERIA','VIA CASTELSARDO, VIA ORISTANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (50,'90003000532','VIA CIPRO','','VIALE EUROPA, VIA LIDO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (51,'90003000533','PIAZZA CIVICA','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (78,'90003000534','BASTIONI CRISTOFORO COLOMBO','VIA CARLO ALBERTO, PIAZZA SULIS','VIA CAVOUR, VIA MAIORCA, VIA DELLA MISERICORDIA, VICOLO PERETTI, BASTIONI MARCO POLO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (118,'90003000513','VIA F.LLI CANELLES','','VIA F.LLI KENNEDY, VIA TODA EDUARD');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (267,'90003000977','VIA SENZA NOME 018 (TAMERICI)','VIA SENZA NOME 031 (DELLE PALME), VIA SENZA NOME 033 (DEGLI ANEMONI)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (268,'90003000978','VIA SENZA NOME 019 (DEI GINEPRI)','','VIA SENZA NOME 020 (DEI PLATANI), VIA SENZA NOME 024 (DELLE VIGNE), VIA SENZA NOME 031 (DELLE PALME)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (269,'90003000979','VIA SENZA NOME 020 (DEI PLATANI)','','VIA SENZA NOME 019 (DEI GINEPRI), VIA SENZA NOME 024 (DELLE VIGNE), VIA SENZA NOME 025 (DEGLI ULIVI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (52,'90003000535','VIA COLUMBANO','PIAZZA MUNICIPIO, VICOLO SERRA','VIA MINERVA, PIAZZA PORTA TERRA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (70,'90003000536','VIA COROS','VIA BARCIA, VIALE DELLA RESISTENZA','VIA VILLAFRANCA DEL PANADES');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (71,'90003000537','VIA CORSICA','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (72,'90003000538','VIA COSTA ENRICO','VIA GARIBALDI GIUSEPPE, VIA LIDO, VIA PAOLI PASQUALE','VIA AZUNI, VIA GALILEO GALILEI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (73,'90003000539','LARGO COSTANTINO NUNZIO','VIA SATTA SEBASTIANO, PIAZZA SENZA NOME 195','VIA DELEDDA GRAZIA, VIA MARCONI GUGLIELMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (74,'90003000540','VIA CRAVELLET','VIA MAZZINI GIUSEPPE, VIA VITTORIO EMANUELE','VIA CARRABUFFAS, VIA PIERINO ENRICO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (75,'90003000541','VIA CRAVELLET TRAV. A','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (76,'90003000542','VIA CRAVELLET TRAV. B','','VIA CRAVELLET, VIA DELEDDA GRAZIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (77,'90003000543','VIA CRETA','VIA DON MINZONI, VIA PISA, VIALE SARDEGNA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (79,'90003000544','VIA CROCE BENEDETTO','VIA F.LLI KENNEDY','VIA DE NICOLA ENRICO TRAV. A, VIA PERPIGNAN');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (80,'90003000545','VIA DALERCI ANTONIO','VIA F.LLI KENNEDY, VIA PUTRANCH J. A.','VIA ARCHIMBAO GABRIEL');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (83,'90003000546','LUNGOMARE DANTE','VIA GRAMSCI ANTONIO, VIA PETRARCA FRANCESCO, PIAZZA SULIS','VIA PERPIGNAN, LUNGOMARE VALENCIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (84,'90003000547','VIA DA VINCI LEONARDO','VIA MACCIOTTA SEBASTIANO, VIA XX SETTEMBRE','VIA FORADADA, VIA GUIXERA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (85,'90003000548','VIA DE BIASE','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (87,'90003000549','VIA DE GASPERI ALCIDE','VIA MONT D''OLLA, VIA VALVERDE, VIA ROSSI','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (88,'90003000550','VIA DE GASPERI ALCIDE TRAV. A','VIA DE GASPERI ALCIDE','VIALE DELLA RESISTENZA, VIA DE GASPERI ALCIDE TRAV. C');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (89,'90003000551','VIA DE GASPERI ALCIDE TRAV. B','','VIA DE GASPERI ALCIDE TRAV. A');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (91,'90003000552','VIA DE GIORGIO GIOVANNI','VIA CASTELSARDO','VIA LA MADDALENA, VIA PAIS GIOVANNI, VIA SENZA NOME 181');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (92,'90003000553','VIA DELEDDA GRAZIA','LARGO ERA ANTONIO, VIA SANT''AGOSTINO','VIA BARRACU MASSIMILIANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (93,'90003000555','VIA DE LIGUORO RINA','','VIA ROCKEFELLER, VIA TARRAGONA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (94,'90003000556','VIA DELITALA GIUSEPPE ALBERTO','VIA CAVOUR','VIA PRINCIPE UMBERTO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (95,'90003000557','VIA DE MURO','VIA GRANDI ACHILLE, VIA VALVERDE','VIA DE BIASE, VIA DE MURO TRAV. A');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (96,'90003000558','VIA DE MURO TRAV. A','VIA DE MURO, VIA VALVERDE I STRADA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (97,'90003000559','VIA DE NICOLA ENRICO','VIA DE NICOLA ENRICO TRAV. A, VIA F.LLI KENNEDY','VIA PERPIGNAN');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (98,'90003000560','VIA DE NICOLA ENRICO TRAV. A','VIA CROCE BENEDETTO, VIA DE NICOLA ENRICO','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (101,'90003000561','VIA DON DEROMA','VIA CAVOUR, BASTIONI MARCO POLO','VIA PRINCIPE UMBERTO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (99,'90003000562','VIA DIEZ SALVATORE','VIA CATALOGNA, VIA GALLURA, VIALE XXIV MAGGIO, VIA VITTORIO VENETO','VIA JOSTO, VIA MICHELANGELO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (100,'90003000563','VIA DI VITTORIO GIUSEPPE','VIA CARRABUFFAS, VIA MONT D''OLLA','VIA FORADADA, VIA GUIXERA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (102,'90003000564','VIA DON GNOCCHI','','VIA VENEZIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (103,'90003000565','VIA DON MINZONI','VIA GARIBALDI GIUSEPPE, VIA PAIS GIOVANNI','VIA DON MINZONI TRAV. A, VIA LIGURIA, STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (104,'90003000566','VIA DON MINZONI TRAV. A','VIA DON MINZONI','VIA SENZA NOME 184 (JUAN MIRÒ), VIA SENZA NOME 187 (SALVADOR DALÌ)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (105,'90003000567','VIA DORE CARMEN','','VIA CANEPA LUIGI, VIA SANT''AGOSTINO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (106,'90003000570','PIAZZA DUOMO','','PIAZZA CIVICA, VIA MAIORCA, VIA SANT''ERASMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (107,'90003000571','VIA EDISON THOMAS ALVA','','VIA PACINOTTI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (108,'90003000572','VIA EINAUDI LUIGI','VIALE GIOVANNI XXIII, VIA MATTEOTTI GIACOMO','VIA EINAUDI LUIGI TRAV. A, LUNGOMARE VALENCIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (109,'90003000573','VIA EINAUDI LUIGI TRAV. A','','VIA EINAUDI LUIGI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (215,'90003000575','VIA PIERINO ENRICO','VIA CRAVELLET','VIA DA VINCI LEONARDO, VIA BARRACU MASSIMILIANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (112,'90003000576','LARGO ERA ANTONIO','VIA DELEDDA GRAZIA, VIA MARCONI GUGLIELMO','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (113,'90003000577','VIALE EUROPA','VIA CASTELSARDO, VIA LIGURIA, VIA ORISTANO, VIA PORTO TORRES, STRADA SENZA NOME 175','STRADA SENZA NOME 171');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (114,'90003000578','VIA FERMI ENRICO','VIA DON MINZONI','VIA GALILEO GALILEI, VIA PACINOTTI, STRADA CONSORTILE UNGIAS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (133,'90003000579','VIA GILBERT FERRET','VIA CAVOUR, VIA PRINCIPE UMBERTO','LARGO SAN FRANCESCO, VIA SIMON');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (117,'90003000580','VIA FLEMING','VIA DON MINZONI, VIA SENZA NOME 185 (LUIGI NONO), VIA SENZA NOME 186 (SALVADOR ESPRIU)','STRADA SENZA NOME 143, VIA SENZA NOME 182 (PABLO PICASSO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (125,'90003000581','VIA FORADADA','VIA DI VITTORIO GIUSEPPE, VIA VALVERDE','VIA CALA LLONGA, VIA FORADADA I TRAV.');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (127,'90003000582','VIA FOSCOLO UGO','LUNGOMARE DANTE','VIA F.LLI KENNEDY, VIA SASSARI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (128,'90003000583','VIA FRANK G.','VIA F.LLI KENNEDY','VIA ARCHIMBAO GABRIEL, VIA PUTRANCH J. A.');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (129,'90003000584','VIA GALILEO GALILEI','VIA DON MINZONI, VIA FERMI ENRICO','VIA COSTA ENRICO, VIA DEGLI ORTI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (130,'90003000585','VIA GALLURA','VIA ASFODELO, VIA DIEZ SALVATORE','VIA DEGLI ORTI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (131,'90003000586','VIA GARIBALDI GIUSEPPE','','VIA CASTELSARDO, VIA DON MINZONI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (132,'90003000587','VIA GENOVA','','VIA CAGLIARI, VIA SASSARI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (134,'90003000588','PIAZZA GINNASIO','','VIA CARLO ALBERTO, VIA MAIORCA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (135,'90003000589','VIA GIOBERTI','VIA CARLO ALBERTO','VIA BARCELONETTA, VIA SIMON');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (136,'90003000590','VIA GIOLITTI GIOVANNI','VIA TOGLIATTI PALMIRO, VIA VALVERDE','VIA CANEPA LUIGI, VIA PALOMBA GIUSEPPE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (137,'90003000591','VIALE GIOVANNI XXIII','','STRADA STATALE N° 292 NORD, VIA SENZA NOME 234, VIA SENZA NOME 236, VIA SENZA NOME 239');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (138,'90003000592','VIA GOCEANO','VIA ASFODELO, VIA DIEZ SALVATORE','VIA CARAVAGGIO, VIA CELLINI BENVENUTO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (139,'90003000593','VIA GRAMSCI ANTONIO','LUNGOMARE DANTE, VIA PETRARCA FRANCESCO, PIAZZA SULIS','VIA MANZONI ALESSANDRO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (140,'90003000594','VIA GRANDI ACHILLE','VIA DE GASPERI ALCIDE, VIA DE MURO','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (141,'90003000595','VIA GUIXERA','VIA DI VITTORIO GIUSEPPE, VIA VALVERDE','VIA CALA LLONGA, VIA FORADADA I TRAV.');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (142,'90003000596','VIA IGLESIAS','VIA AGGIUS, VIA DON MINZONI','VIA CASTELSARDO, VIALE SARDEGNA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (146,'90003000597','VIA JOSTO','VIA GARIBALDI GIUSEPPE, VIA DEGLI ORTI','VIA DIEZ SALVATORE, VIA VITTORIO EMANUELE, VIA SENZA NOME 190');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (120,'90003000598','VIA F.LLI KENNEDY','LARGO SAN FRANCESCO, PIAZZA SULIS, VIA XX SETTEMBRE','VIA DE GASPERI ALCIDE, VIALE DELLA RESISTENZA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (121,'90003000599','VIA F.LLI KENNEDY VIC/A','VIA F.LLI KENNEDY, VIA SASSARI','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (122,'90003000600','VIA F.LLI KENNEDY VIC/B','','VIA F.LLI KENNEDY');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (123,'90003000601','VIA F.LLI KENNEDY VIC/C','','VIA F.LLI KENNEDY');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (147,'90003000602','VIA LACCU SIMON','VIA CAVOUR, VIA ZACCARIA','VIA PRINCIPE UMBERTO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (63,'90003001144','STRADA CONSORTILE PUNTA MORO','STRADA CONSORTILE UNGIAS, VIA SENZA NOME 200','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (148,'90003000603','VIA LA MADDALENA','VIA AGGIUS, VIA CASTELSARDO','VIA DE GIORGIO GIOVANNI, VIA PORTO TORRES, VIA SENZA NOME 181');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (149,'90003000604','VIA LA MARMORA ALBERTO','VIA ELEONORA D''ARBOREA, VIA CATALOGNA, VIA GARIBALDI GIUSEPPE','VIA NUORO, VIA SANT''AGOSTINO, VIA XX SETTEMBRE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (150,'90003000606','VIA LAZZARETTO','VIA CAVOUR','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (151,'90003000607','VIA LEOPARDI GIACOMO','LUNGOMARE DANTE','VIA GRAMSCI ANTONIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (152,'90003000608','VIA LIDO','VIA COSTA ENRICO, VIA GARIBALDI GIUSEPPE, VIA LIDO VIC/A','VIA LIGURIA, VIA MALTA, VIALE I MAGGIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (153,'90003000609','VIA LIDO VIC/A','','VIA LIDO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (154,'90003000611','VIA LIGURIA','VIA CALABRIA, VIA LIDO, VIALE I MAGGIO','VIA DON MINZONI, STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (155,'90003000612','VIA LIGURIA TRAV. A','','VIA DON MINZONI, VIA LIGURIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (156,'90003000613','VIA LISTZ','','VIALE GIOVANNI XXIII, VIA PAGANINI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (157,'90003000614','VIA LO FRASSO','VIA MAZZINI GIUSEPPE, VIA VITTORIO EMANUELE','PIAZZA DELLA MERCEDE, VIA NUORO, VIA TARRAGONA, VIA XX SETTEMBRE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (158,'90003000615','VIA LOGUDORO','VIA ASFODELO, VIA DIEZ SALVATORE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (159,'90003000616','VIA MACCIOTTA SEBASTIANO','VIA CRAVELLET, VIA DA VINCI LEONARDO','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (160,'90003000617','VIA MACHIN AMBROGIO','VIA CARLO ALBERTO','VIA BARCELONETTA, VIA SIMON');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (162,'90003000618','BASTIONI MAGELLANO','VIA BERTOLOTTI FRANCESCO, VIA PORTA A MARE','PIAZZETTA MOLO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (163,'90003000619','VIA MAIORCA','PIAZZA CIVICA, PIAZZA DUOMO','BASTIONI CRISTOFORO COLOMBO, VIA MINORCA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (164,'90003000620','VIA MALTA','VIA LIDO, VIA SICILIA','VIA DON MINZONI, VIALE SARDEGNA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (165,'90003000621','VIA MALTA TRAV. A','','VIA MALTA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (166,'90003000622','VIA MALTA TRAV. B','','VIA MALTA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (167,'90003000623','VIA MANCA MAURO','VIA DE GASPERI ALCIDE','VIA DE BIASE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (168,'90003000624','VIA MANNO GIUSEPPE','PIAZZA DUOMO, VIA OSPEDALE','BASTIONI MARCO POLO, VIA SANTA BARBARA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (169,'90003000625','VIA MANZONI ALESSANDRO','VIA GRAMSCI ANTONIO','VIA CANEPA LUIGI, VIA SANT''AGOSTINO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (170,'90003000626','VIA MARCONI GUGLIELMO','VIA IV NOVEMBRE, VIA SANT''AGOSTINO','VIA BARRACU MASSIMILIANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (171,'90003000627','VIA MARCONI GUGLIELMO TRAV. A','','VIA CAVANNA, VIA DELEDDA GRAZIA, VIA MARCONI GUGLIELMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (173,'90003000628','VIA MARONGIU ANTONIO','VIA CANEPA LUIGI, VIA MATTEOTTI GIACOMO, VIA TOGLIATTI PALMIRO','VIALE GIOVANNI XXIII, VIA MATTEI ENRICO, VIA ROCKEFELLER');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (174,'90003000629','VIA MATTEI ENRICO','VIA F.LLI KENNEDY, VIA VANONI EZIO','VIALE GIOVANNI XXIII, VIA MARONGIU ANTONIO, VIA MORANDI RODOLFO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (175,'90003000630','VIA MATTEOTTI GIACOMO','VIA MARONGIU ANTONIO, VIA TOGLIATTI PALMIRO, VIA VALVERDE','VIA EINAUDI LUIGI, VIALE GIOVANNI XXIII, VIA ROCKEFELLER');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (176,'90003000631','VIA MAZZINI GIUSEPPE','LARGO SAN FRANCESCO, VIA SASSARI','VIA SENZA NOME 198');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (178,'90003000632','PIAZZA DELLA MERCEDE','','VIALE GIOVANNI XXIII, VIA LO FRASSO, VIA NUORO, VIA TARRAGONA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (179,'90003000633','VIA MICHELANGELO','','VIA DIEZ SALVATORE, VIA VITTORIO EMANUELE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (180,'90003000634','VIA MINERVA','PIAZZA CIVICA, VIA COLUMBANO','VICOLO ADAMI, VIA ROMA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (181,'90003000635','VIA MINORCA','','VIA CARLO ALBERTO, VIA MAIORCA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (182,'90003000636','VIA DELLA MISERICORDIA','VIA CAVOUR, BASTIONI CRISTOFORO COLOMBO, VICOLO PERETTI, BASTIONI MARCO POLO, VIA ZACCARIA','VIA ARDUINO RAFFAELE, VIA MAIORCA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (183,'90003000637','PIAZZETTA MOLO','VIA OSPEDALE, VIA SANT''ERASMO','BASTIONI MAGELLANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (184,'90003000638','VIA MONT D''OLLA','VIA DE GASPERI ALCIDE, VIA DI VITTORIO GIUSEPPE, VIA VALVERDE','VIA CARRABUFFAS, VIA SENZA NOME 197');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (185,'90003000640','VIA MONTSERRAT','','VIA CARBIA, VIA SANT''ANNA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (186,'90003000641','VIA MORANDI RODOLFO','VIA DELLE NAZIONI UNITE','VIA MATTEI ENRICO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (187,'90003000642','VIA MOZART','VIALE GIOVANNI XXIII','VIA PAGANINI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (188,'90003000643','PIAZZA MUNICIPIO','VIA COLUMBANO, VIA ROMA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (189,'90003000644','VIA NAPOLI','VIA AMALFI, VIA DON MINZONI, VIA ORISTANO','VIA TIZIANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (190,'90003000645','VIA DELLE NAZIONI UNITE','VIA PALOMBA GIUSEPPE, VIA TARRAGONA','VIA F.LLI KENNEDY, VIA SASSARI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (191,'90003000646','VIA NULAURO','VIALE DELLA RESISTENZA','VIA SANT''IMBENIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (192,'90003000647','VIA NUORO','VIA LA MARMORA ALBERTO, VIA ROTH ANGELO, VIA SANT''AGOSTINO','VIA LO FRASSO, PIAZZA DELLA MERCEDE, VIA TARRAGONA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (194,'90003000648','VIA ORISTANO','VIA DON MINZONI, VIA NAPOLI, VIALE SARDEGNA','VIA F.LLI CERVI, VIALE EUROPA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (196,'90003000649','VIA DEGLI ORTI','VIA GALLURA, VIA GARIBALDI GIUSEPPE, VIALE XXIV MAGGIO','VIA DEGLI ORTI TRAV. B, VIA VOLTA ALESSANDRO, STRADA CONSORTILE MONTAGNESE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (197,'90003000650','VIA DEGLI ORTI TRAV. A','','VIA ASFODELO, VIA DEGLI ORTI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (198,'90003000651','VIA DEGLI ORTI TRAV. B','','VIA DEGLI ORTI, VIA PACINOTTI, STRADA CONSORTILE MONTAGNESE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (199,'90003000652','VIA OSPEDALE','PIAZZA DUOMO, VIA MANNO GIUSEPPE','VIA BERTOLOTTI FRANCESCO, PIAZZETTA MOLO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (201,'90003000653','VIA PACINOTTI','VIA GALILEO GALILEI, VIA PAOLI PASQUALE, VIA VOLTA ALESSANDRO','VIA FERMI ENRICO, VIA DEGLI ORTI TRAV. B, STRADA CONSORTILE UNGIAS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (202,'90003000654','VIA PAGANINI','VIA LISTZ, VIA MOZART','VIA VIVALDI ANTONIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (203,'90003000655','VIA PAIS GIOVANNI','VIA DON MINZONI','VIA DE GIORGIO GIOVANNI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (204,'90003000656','VIA PALOMBA GIUSEPPE','VIA MANZONI ALESSANDRO, VIA ROSSINI GIOACCHINO','VIA MARONGIU ANTONIO, VIA MATTEOTTI GIACOMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (205,'90003000657','VIA PALOMBA GIUSEPPE VIC/A','VIA PALOMBA GIUSEPPE','VIA ROCKEFELLER, VIA TARRAGONA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (206,'90003000658','VIA PANTELLERIA','VIA F.LLI CERVI, VIA LIDO','VIALE EUROPA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (207,'90003000659','VIA PAOLI PASQUALE','VIA AZUNI, VIA GALILEO GALILEI, VIA PACINOTTI','VIA ANGIOY G. M.');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (211,'90003000660','VIA PASCOLI GIOVANNI','LUNGOMARE DANTE, VIA GRAMSCI ANTONIO','VIALE GIOVANNI XXIII, VIA SASSARI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (212,'90003000661','VICOLO PERETTI','','VIA CAVOUR, BASTIONI CRISTOFORO COLOMBO, VIA DELLA MISERICORDIA, BASTIONI MARCO POLO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (213,'90003000662','VIA PERPIGNAN','VIA CROCE BENEDETTO, LUNGOMARE DANTE','VIA BANYOLAS, VIA F.LLI KENNEDY');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (214,'90003000663','VIA PETRARCA FRANCESCO','LUNGOMARE DANTE, VIA GRAMSCI ANTONIO','VIA F.LLI KENNEDY, VIA SASSARI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (216,'90003000664','VIA PISA','VIA AMALFI, VIA CRETA, VIA DON MINZONI','VIA PISA TRAV. B');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (217,'90003000665','VIA PISA TRAV. A','','VIA PISA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (218,'90003000666','VIA PISA TRAV. B','','VIA PISA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (172,'90003000667','BASTIONI MARCO POLO','VIA CAVOUR, BASTIONI CRISTOFORO COLOMBO, VIA DELLA MISERICORDIA, VICOLO PERETTI','VIA MANNO GIUSEPPE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (220,'90003000668','VIA PORRINO ENNIO','VIA CANEPA LUIGI, VIA CARRABUFFAS, VIA SANT''AGOSTINO','VIA ROCKEFELLER, VIA TARRAGONA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (224,'90003000669','VIA PORTO TORRES','VIA DON MINZONI, VIA LA MADDALENA','VIA AGGIUS, VIA CASTELSARDO, VIALE EUROPA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (143,'90003000670','VIALE I MAGGIO','VIA LIDO, VIA LIGURIA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (225,'90003000671','VIA PRINCIPE UMBERTO','VIA DON DEROMA, VIA ROMA','VIA DELLA MISERICORDIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (228,'90003000672','VIA PUCCINI GIACOMO','VIA CANEPA LUIGI, VIA PALOMBA GIUSEPPE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (229,'90003000673','VIA PUTRANCH J. A.','','VIA DALERCI ANTONIO, VIA FRANK G.');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (145,'90003000674','VIA IV NOVEMBRE','VIA CATALOGNA, VIA VITTORIO EMANUELE','VIA MARCONI GUGLIELMO, VIA XX SETTEMBRE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (231,'90003000675','VIALE DELLA RESISTENZA','VIA SANT''IMBENIA, PIAZZALE EL TRO'' (VIA JOSE'' MARIA ESCRIVA), LUNGOMARE VALENCIA, STRADA PROVINCIALE N° 105','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (233,'90003000678','VIA ROCKEFELLER','VIA DE LIGUORO RINA, VIA MANZONI ALESSANDRO','VIA MARONGIU ANTONIO, VIA MATTEOTTI GIACOMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (234,'90003000679','VIA ROMA','VIA CAVOUR, VIA SANTA BARBARA','VIA BARCELONETTA, PIAZZA PORTA TERRA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (124,'90003000680','VIA F.LLI ROSSELLI','VIA ROSSI','VIA CANEPA LUIGI, VIA TOGLIATTI PALMIRO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (236,'90003000681','VIA ROSSINI GIOACCHINO','VIA MANZONI ALESSANDRO, VIA PALOMBA GIUSEPPE, VIA SANT''AGOSTINO','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (237,'90003000682','VIA ROSSINI GIOACCHINO TRAV. A','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (238,'90003000683','VIA ROTH ANGELO','VIA NUORO, VIA VERDI GIUSEPPE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (240,'90003000684','VIA RUOTA','','VIA CAVOUR');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (245,'90003000685','VIA SANT''AGOSTINO','VIA LA MARMORA ALBERTO, VIA MARCONI GUGLIELMO, VIA NUORO','VIA CARRABUFFAS, VIA PORRINO ENNIO, VIA VALVERDE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (248,'90003000686','LARGO SANTI ANGELI','VIA CATALOGNA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (243,'90003000689','VIA SANTA BARBARA','VIA CAVOUR, VIA MANNO GIUSEPPE, VIA ROMA','VIA BERTOLOTTI FRANCESCO, PIAZZA SANTA CROCE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (244,'90003000690','PIAZZA SANTA CROCE','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (247,'90003000691','VIA SANT''ERASMO','PIAZZA DUOMO','VIA BERTOLOTTI FRANCESCO, PIAZZETTA MOLO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (241,'90003000692','LARGO SAN FRANCESCO','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (249,'90003000695','VIA SANT''IMBENIA','','VIA NULAURO, VIALE DELLA RESISTENZA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (242,'90003000696','VIA SANNINO','','PIAZZA SANTA CROCE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (250,'90003000697','VIA SANZIO RAFFAELLO','VIA MAZZINI GIUSEPPE, VIA VITTORIO EMANUELE','VIA DELEDDA GRAZIA, VIA MARCONI GUGLIELMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (251,'90003000698','VIALE SARDEGNA','VIA CASTELSARDO, VIA IGLESIAS, VIA ORISTANO','LARGO CAPRERA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (252,'90003000699','VIA SASSARI','BASTIONI MADDALENA, VIA SENZA NOME 084 (SCALO TARANTIELLO)','VIA EINAUDI LUIGI, VIA MATTEI ENRICO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (253,'90003000700','VIA SATTA SEBASTIANO','VIA BERNINI GIOVANNI LORENZO, VIA DIEZ SALVATORE','VIA CARRABUFFAS, LARGO COSTANTINO NUNZIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (477,'90003000701','VICOLO SERRA','PIAZZA CIVICA, VIA COLUMBANO','VIA ROMA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (478,'90003000702','VIA SICILIA','VIA MALTA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (480,'90003000703','VIA SIMON','VIA GILBERT FERRET, VIA GIOBERTI, LARGO SAN FRANCESCO','VIA MACHIN AMBROGIO, PIAZZA PORTA TERRA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (483,'90003000704','VIA SPANO GIOVANNI','VIA ASFODELO, VIA DEGLI ORTI','VIA GARIBALDI GIUSEPPE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (484,'90003000705','LARGO DELLO SPERONE','','LARGO CAPRERA, VIA DON MINZONI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (499,'90003000706','VIA STURZO DON LUIGI','VIA TOGLIATTI PALMIRO, VIA VALVERDE','VIA CANEPA LUIGI, VIA PALOMBA GIUSEPPE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (500,'90003000707','PIAZZA SULIS','','VIA CARDUCCI GIOSUE'', LUNGOMARE DANTE, VIA GRAMSCI ANTONIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (501,'90003000708','VIA TARRAGONA','VIA LO FRASSO, PIAZZA DELLA MERCEDE, VIA NUORO, VIA VERDI GIUSEPPE','VIA MARONGIU ANTONIO, VIA MATTEOTTI GIACOMO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (502,'90003000709','VICOLO DEL TEATRO','VIA CARLO ALBERTO','VIA ARDUINO RAFFAELE, VIA MAIORCA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (49,'90003000739','VIA CHERSO','LARGO FIUME, LUNGOMARE ROVIGNO','VIA FIUME, VIA ORSERA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (81,'90003000740','VIA DALMAZIA','LUNGOMARE ROVIGNO','VIA PARENZO, VIA SENZA NOME 258 (SPALATO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (82,'90003000741','VIA DALMAZIA TRAV. A','VIA DALMAZIA, VIA PARENZO TRAV.A','VIA PARENZO TRAV.B');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (116,'90003000742','VIA FIUME','VIA CHERSO, LUNGOMARE ROVIGNO, VIA SENZA NOME 257 (UDINE)','Via Senza Nome 008');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (115,'90003000743','LARGO FIUME','','VIA CHERSO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (144,'90003000744','VIA ISTRIA','','PIAZZA VENEZIA GIULIA, VIA ZARA, STRADA S.S. 127/BIS Km 4, Via Strada Statale 127bis - Porto Conte, VIA S.S 291');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (195,'90003000745','VIA ORSERA','VIA CHERSO, LUNGOMARE ROVIGNO','VIA ZARA, Via Senza Nome 008');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (208,'90003000747','VIA PARENZO','PIAZZA VENEZIA GIULIA','VIA DALMAZIA, VIA ZARA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (219,'90003000748','VIA POLA','VIA FIUME, VIA ORSERA','LUNGOMARE ROVIGNO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (239,'90003000749','LUNGOMARE ROVIGNO','VIA ORSERA, Via Strada Statale 127bis - Porto Conte','VIA DALMAZIA, VIA ZARA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (193,'90003000752','PIAZZA OLBIA','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (200,'90003000753','VIA OZIERI','PIAZZA OLBIA, VIA SILA, VIA TEMPIO','VIA SENZA NOME 057 (GIA'' STRADA VICINALE ZIRRA IN SASSARI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (479,'90003000754','VIA SILA','PIAZZA OLBIA, VIA OZIERI','VIA SENZA NOME 050');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (503,'90003000755','VIA TEMPIO','PIAZZA OLBIA, VIA OZIERI','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (37,'90003000858','VIA CARBIA TRAV.A','','VIA CARBIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (126,'90003000865','VIA FORADADA I TRAV.','VIA FORADADA, VIA GUIXERA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (235,'90003000867','VIA ROSSI','','VIA DE GASPERI ALCIDE, VIA F.LLI ROSSELLI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (232,'90003000868','VIALE DELLA RESISTENZA TRAV. C','VIALE DELLA RESISTENZA, VIA SENZA NOME 239','VIA SENZA NOME 243');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (177,'90003000883','VIA MAZZINI GIUSEPPE TRAV.A','VIA MAZZINI GIUSEPPE, VIA XX SETTEMBRE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (86,'90003000890','VIA DE BIASE VIC.A','VIA DE BIASE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (210,'90003000891','VIA PARENZO TRAV.B','VIA SENZA NOME 258 (SPALATO)','VIA DALMAZIA TRAV. A, Via Senza Nome 003');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (209,'90003000892','VIA PARENZO TRAV.A','','VIA DALMAZIA TRAV. A, VIA SENZA NOME 258 (SPALATO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (222,'90003000897','PIAZZA PORTA TERRA','VIA SASSARI, VIA SIMON','VIA COLUMBANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (90,'90003000898','VIA DE GASPERI ALCIDE TRAV. C','VIA DE GASPERI ALCIDE TRAV. A, VIA SENZA NOME 241','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (161,'90003000909','BASTIONI MADDALENA','VIA SASSARI','PIAZZA CIVICA, VIA BANCHINA DOGANA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (246,'90003000912','VIA SANT''ANNA','VIA BARCIA, VIA F.LLI KENNEDY, VIALE DELLA RESISTENZA','VIA MONTSERRAT, STRADA CONSORTILE S. ANNA POLLINA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (485,'90003000935','STRADA S.S. 127/BIS Km 4','VIA ISTRIA, VIA ZARA, Via Strada Statale 127bis - Porto Conte, VIA S.S 291','VIA SENZA NOME 026 (DEI PALMIZI), VIA SENZA NOME 027 (PORTO CONTE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (254,'90003000943','Via Senza Nome 001','','LUNGOMARE ROVIGNO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (256,'90003000945','Via Senza Nome 006','','Via Strada Statale 127bis - Porto Conte, Via Senza Nome 007');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (257,'90003000946','Via Senza Nome 007','Via Strada Statale 127bis - Porto Conte, Via Senza Nome 006','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (255,'90003000947','Via Senza Nome 003','VIA PARENZO TRAV.B','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (258,'90003000953','Via Senza Nome 008','VIA FIUME, VIA ORSERA','VIA FIUME, VIA ORSERA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (322,'90003001018','VIA SENZA NOME 084 (SCALO TARANTIELLO)','','VIA SASSARI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (469,'90003000940','VIA SENZA NOME 254 (MARTIRI DELLE FOIBE)','','LUNGOMARE ROVIGNO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (292,'90003001024','VIA SENZA NOME 048','VIA SILA','STRADA PROVINCIALE 55 BIS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (294,'90003001025','VIA SENZA NOME 050','STRADA PROVINCIALE 55 BIS, VIA SENZA NOME 055, VIA SENZA NOME 059','VIA SILA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (295,'90003001026','VIA SENZA NOME 051 (GIA'' VIA BUDDUSO'' IN SASSARI)','STRADA PROVINCIALE 55 BIS','VIA SENZA NOME 055');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (296,'90003001027','VIA SENZA NOME 052 (GIA'' VIA OSCHIRI IN SASSARI)','STRADA PROVINCIALE 55 BIS','VIA SENZA NOME 055');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (297,'90003001028','VIA SENZA NOME 053','STRADA PROVINCIALE 55 BIS','VIA SENZA NOME 054, VIA SENZA NOME 078');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (298,'90003001029','VIA SENZA NOME 054','VIA SENZA NOME 053, VIA SENZA NOME 078','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (323,'90003001056','VIA SENZA NOME 085','VIA S.S 291','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (324,'90003001057','VIA SENZA NOME 086','VIA S.S 291','VIA SENZA NOME 087');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (325,'90003001058','VIA SENZA NOME 087','VIA SENZA NOME 086, VIA SENZA NOME 090','VIA SENZA NOME 245');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (326,'90003001059','VIA SENZA NOME 088','','VIA STRADA PROVINCIALE N° 44');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (327,'90003001060','VIA SENZA NOME 089','','VIA STRADA PROVINCIALE N° 44');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (328,'90003001061','VIA SENZA NOME 090','VIA STRADA PROVINCIALE N° 44','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (495,'90003001062','VIA STRADA PROVINCIALE N� 44','VIA S.S 291','STRADA S.S.VAR. CALICH');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (329,'90003001063','VIA SENZA NOME 091','VIA STRADA PROVINCIALE N° 44','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (330,'90003001064','VIA SENZA NOME 092','VIA STRADA PROVINCIALE N° 44','VIA SENZA NOME 093');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (331,'90003001065','VIA SENZA NOME 093','VIA SENZA NOME 246','VIA SENZA NOME 092');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (460,'90003001066','VIA SENZA NOME 245','VIA SENZA NOME 092, VIA STRADA PROVINCIALE 5M','VIA SENZA NOME 087');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (494,'90003001067','VIA STRADA PROVINCIALE 5M','VIA STRADA PROVINCIALE N° 44','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (461,'90003001068','VIA SENZA NOME 246','VIA STRADA PROVINCIALE N° 44, VIA SENZA NOME 093','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (462,'90003001069','VIA SENZA NOME 247','VIA STRADA PROVINCIALE N° 44','VIA SENZA NOME 102, STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 133 (Gi�  STRADA CASSONEDDA IN OLMEDO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (463,'90003001070','VIA SENZA NOME 248','VIA STRADA PROVINCIALE N° 44','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (464,'90003001071','VIA SENZA NOME 249','VIA S.S 291','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (465,'90003001072','VIA SENZA NOME 250','VIA S.S 291, VIA SENZA NOME 071','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (466,'90003001073','VIA SENZA NOME 251','VIA S.S 291, VIA SENZA NOME 094','VIA STRADA PROVINCIALE N° 44');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (482,'90003001074','VIA S.P. 44','VIA S.S 291, VIA SENZA NOME 094','VIA STRADA PROVINCIALE N° 44');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (332,'90003001075','VIA SENZA NOME 094','','VIA SENZA NOME 251, VIA S.P. 44');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (333,'90003001076','VIA SENZA NOME 095','VIA STRADA PROVINCIALE N° 44','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (334,'90003001077','VIA SENZA NOME 096','VIA STRADA PROVINCIALE N° 44, VIA SENZA NOME 097','VIA SENZA NOME 095');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (335,'90003001078','VIA SENZA NOME 097','VIA SENZA NOME 096, STRADA S.S.VAR. CALICH','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (336,'90003001079','VIA SENZA NOME 098','VIA SENZA NOME 099','VIA S.S 291, VIA SENZA NOME 085');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (337,'90003001080','VIA SENZA NOME 099','VIA SENZA NOME 098','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (338,'90003001081','VIA SENZA NOME 100','VIA SENZA NOME 095','VIA SENZA NOME 247, VIA SENZA NOME 248, STRADA SENZA NOME 109');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (339,'90003001082','VIA SENZA NOME 101','VIA SENZA NOME 247','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (340,'90003001083','VIA SENZA NOME 102','','VIA SENZA NOME 247, STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 124');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (488,'90003001084','STRADA S.S.VAR. CALICH','VIA S.S 291','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (341,'90003001085','STRADA SENZA NOME 103','STRADA S.S.VAR. CALICH, STRADA CONSORTILE LA RUCCHETTA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (343,'90003001088','STRADA SENZA NOME 107','VIA SENZA NOME 247, STRADA SENZA NOME 111','STRADA SENZA NOME 109, STRADA SENZA NOME 121');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (345,'90003001089','STRADA SENZA NOME 109','VIA SENZA NOME 247, VIA SENZA NOME 100, STRADA SENZA NOME 111','STRADA SENZA NOME 107, STRADA SENZA NOME 115');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (347,'90003001090','STRADA SENZA NOME 111','STRADA SENZA NOME 107','STRADA SENZA NOME 109');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (350,'90003001092','STRADA SENZA NOME 115','STRADA SENZA NOME 107, STRADA SENZA NOME 109','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (354,'90003001095','STRADA SENZA NOME 121','VIA SENZA NOME 247','VIA SENZA NOME 246, STRADA SENZA NOME 107');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (357,'90003001097','STRADA SENZA NOME 125','STRADA SENZA NOME 127','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (359,'90003001098','STRADA SENZA NOME 127','STRADA SENZA NOME 125','STRADA S.S.VAR. CALICH');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (362,'90003001100','STRADA SENZA NOME 131','STRADA S.S.VAR. CALICH','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (342,'90003001102','STRADA SENZA NOME 106','','STRADA S.S.VAR. CALICH, STRADA CONSORTILE LA RUCCHETTA, STRADA CONSORTILE LA RUCCHETTA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (344,'90003001103','STRADA SENZA NOME 108','','STRADA CONSORTILE LA RUCCHETTA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (493,'90003001104','STRADA STRADA PROVINCIALE 44','','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (348,'90003001106','STRADA SENZA NOME 112','STRADA CONSORTILE LA RUCCHETTA, STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 153','STRADA CONSORTILE UNGIAS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (68,'90003001107','STRADA CONSORTILE UNGIAS','VIA FERMI ENRICO, VIA PACINOTTI','STRADA SENZA NOME 112, STRADA STRADA PRIVATA 30');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (349,'90003001108','STRADA SENZA NOME 114','','STRADA SENZA NOME 112');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (491,'90003001109','STRADA STRADA PRIVATA 6','STRADA STRADA PROVINCIALE 42','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (351,'90003001110','STRADA SENZA NOME 116','','STRADA SENZA NOME 112');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (352,'90003001112','STRADA SENZA NOME 118','','STRADA CONSORTILE SAN QUIRICO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (353,'90003001113','STRADA SENZA NOME 120','','STRADA CONSORTILE FIGURUJA, STRADA SENZA NOME 130');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (355,'90003001115','STRADA SENZA NOME 122','','STRADA CONSORTILE SAN QUIRICO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (356,'90003001116','STRADA SENZA NOME 124','VIA SENZA NOME 102, STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 128','STRADA SENZA NOME 155, STRADA SENZA NOME 156');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (358,'90003001117','STRADA SENZA NOME 126','STRADA SENZA NOME 124','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (360,'90003001118','STRADA SENZA NOME 128','STRADA SENZA NOME 124, STRADA SENZA NOME 133 (Gi�  STRADA CASSONEDDA IN OLMEDO)','STRADA CONSORTILE FIGURUJA, STRADA SENZA NOME 130, STRADA STRADA PRIVATA 30');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (361,'90003001119','STRADA SENZA NOME 130','STRADA SENZA NOME 120, STRADA SENZA NOME 128, STRADA STRADA PRIVATA 30','VIA S.P. 19');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (363,'90003001122','STRADA SENZA NOME 132','STRADA CONSORTILE FIGURUJA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (364,'90003001123','STRADA SENZA NOME 133 (Gi� STRADA CASSONEDDA IN OLMEDO)','VIA SENZA NOME 247, STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 128','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (366,'90003001124','STRADA SENZA NOME 135','','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (367,'90003001125','STRADA SENZA NOME 136','','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (368,'90003001126','STRADA SENZA NOME 137','','STRADA STRADA PROVINCIALE 42, STRADA CONSORTILE SAN QUIRICO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (369,'90003001127','STRADA SENZA NOME 138','','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (370,'90003001134','STRADA SENZA NOME 140','','STRADA SENZA NOME 112');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (371,'90003001140','STRADA SENZA NOME 141','STRADA SENZA NOME 112, STRADA CONSORTILE UNGIAS','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (372,'90003001141','STRADA SENZA NOME 142','','STRADA CONSORTILE UNGIAS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (373,'90003001146','STRADA SENZA NOME 143','','VIA FLEMING');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (374,'90003001147','STRADA SENZA NOME 144','STRADA STRADA PROVINCIALE 42','STRADA SENZA NOME 146, STRADA SENZA NOME 252');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (375,'90003001148','STRADA SENZA NOME 145','','STRADA SENZA NOME 144, STRADA SENZA NOME 147, STRADA SENZA NOME 252');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (376,'90003001149','STRADA SENZA NOME 146','STRADA SENZA NOME 144, STRADA SENZA NOME 149, STRADA SENZA NOME 252','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (377,'90003001150','STRADA SENZA NOME 147','','STRADA SENZA NOME 145, STRADA SENZA NOME 252');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (378,'90003001151','STRADA SENZA NOME 148','','STRADA SENZA NOME 252');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (492,'90003001105','STRADA STRADA PROVINCIALE 42','STRADA STRADA PRIVATA 6, VIA DON MINZONI, VIA LIGURIA, Viale Burruni Salvatore','STRADA SENZA NOME 144');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (379,'90003001152','STRADA SENZA NOME 149','STRADA SENZA NOME 144, STRADA SENZA NOME 146','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (380,'90003001153','STRADA SENZA NOME 150','STRADA CONSORTILE LA RUCCHETTA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (381,'90003001157','STRADA SENZA NOME 151','','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (382,'90003001158','STRADA SENZA NOME 152','','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (383,'90003001161','STRADA SENZA NOME 153','','STRADA CONSORTILE LA RUCCHETTA, STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 112');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (384,'90003001163','STRADA SENZA NOME 154','STRADA SENZA NOME 112','STRADA SENZA NOME 160');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (385,'90003001168','STRADA SENZA NOME 155','','STRADA SENZA NOME 124');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (28,'90003001188','Viale Burruni Salvatore','STRADA STRADA PROVINCIALE 42','VIALE I MAGGIO, Via Strada Statale 127bis - Porto Conte');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (386,'90003001169','STRADA SENZA NOME 156','','STRADA SENZA NOME 124');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (490,'90003001172','STRADA STRADA PRIVATA 30','STRADA CONSORTILE UNGIAS','STRADA SENZA NOME 128, STRADA SENZA NOME 130');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (387,'90003001177','STRADA SENZA NOME 158','','STRADA STRADA PROVINCIALE 42');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (388,'90003001181','STRADA SENZA NOME 159','','STRADA SENZA NOME 154');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (389,'90003001182','STRADA SENZA NOME 160','','STRADA SENZA NOME 154');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (390,'90003001183','STRADA SENZA NOME 161','','STRADA SENZA NOME 154');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (391,'90003001184','STRADA SENZA NOME 162','','STRADA SENZA NOME 154');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (497,'90003000944','Via Strada Statale 127bis - Porto Conte','VIALE I MAGGIO','VIA ISTRIA, VIA ZARA, STRADA S.S. 127/BIS Km 4, Via Senza Nome 006, VIA S.S 291');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (392,'90003001185','STRADA SENZA NOME 163','','STRADA SENZA NOME 154');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (393,'90003001186','STRADA SENZA NOME 164','STRADA SENZA NOME 154','STRADA SENZA NOME 154');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (394,'90003001189','STRADA SENZA NOME 166','STRADA SENZA NOME 167','Viale Burruni Salvatore');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (395,'90003001190','STRADA SENZA NOME 167','STRADA SENZA NOME 168, STRADA SENZA NOME 169','Viale Burruni Salvatore, STRADA SENZA NOME 166');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (396,'90003001191','STRADA SENZA NOME 168','STRADA SENZA NOME 167, STRADA SENZA NOME 169','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (397,'90003001192','STRADA SENZA NOME 169','STRADA SENZA NOME 167, STRADA SENZA NOME 168, STRADA SENZA NOME 175, STRADA SENZA NOME 179','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (422,'90003001229','VIA SENZA NOME 203','VIA SENZA NOME 202, VIA S.S. 127 BIS (VIALE MEDITERRANEO)','VIA SENZA NOME 204');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (423,'90003001230','VIA SENZA NOME 204','VIA SENZA NOME 203, VIA SENZA NOME 205','VIA SENZA NOME 206, VIA SENZA NOME 207');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (424,'90003001231','VIA SENZA NOME 205','','VIA SENZA NOME 202, VIA SENZA NOME 204');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (346,'90003001145','STRADA SENZA NOME 110','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (425,'90003001232','VIA SENZA NOME 206','VIA SENZA NOME 202, VIA SENZA NOME 204','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (426,'90003001233','VIA SENZA NOME 207','VIA SENZA NOME 202, VIA SENZA NOME 204','VIA SENZA NOME 208');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (427,'90003001234','VIA SENZA NOME 208','VIA SENZA NOME 207','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (428,'90003001235','VIA SENZA NOME 209 (VIA MOSSA ANTONI SIMON)','VIA VITTORIO EMANUELE, VIA S.S. 127 BIS (VIALE MEDITERRANEO)','VIA DEGLI ORTI, VIA SENZA NOME 221 (IL CARMINE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (467,'90003001165','STRADA SENZA NOME 252','STRADA SENZA NOME 144, STRADA SENZA NOME 146, STRADA SENZA NOME 148','STRADA SENZA NOME 145, STRADA SENZA NOME 147');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (498,'90003000993','VIA STRADA STATALE 127BIS - PORTO CONTE','STRADA S.S. 127/BIS Km 4, VIA SENZA NOME 034','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (283,'90003000995','VIA SENZA NOME 035','VIA STRADA STATALE 127BIS - PORTO CONTE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (284,'90003000996','VIA SENZA NOME 036','','VIA STRADA STATALE 127BIS - PORTO CONTE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (285,'90003000998','VIA SENZA NOME 038','','STRADA PROVINCIALE 55 BIS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (286,'90003001000','VIA SENZA NOME 039 (GORGONIA)','','VIA STRADA PROVINCIALE N° 55');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (287,'90003001002','VIA SENZA NOME 040 (GIOIOSA)','VIA STRADA PROVINCIALE N° 55','VIA SENZA NOME 041 (DELLE PRIGIONETTE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (288,'90003001003','VIA SENZA NOME 041 (DELLE PRIGIONETTE)','VIA SENZA NOME 040 (GIOIOSA)','VIA STRADA PROVINCIALE N° 55');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (289,'90003001004','VIA SENZA NOME 043','VIA STRADA PROVINCIALE N° 55','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (290,'90003001005','VIA SENZA NOME 044','VIA STRADA PROVINCIALE N° 55','VIA STRADA PROVINCIALE N° 55');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (291,'90003001009','VIA SENZA NOME 047','Via Senza Nome 013','Via Senza Nome 011, Via Senza Nome 012');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (299,'90003001030','VIA SENZA NOME 055','VIA SENZA NOME 050, VIA SENZA NOME 051 (GIA'' VIA BUDDUSO'' IN SASSARI)','VIA SENZA NOME 052 (GIA'' VIA OSCHIRI IN SASSARI), VIA SENZA NOME 053, VIA SENZA NOME 079');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (487,'90003001031','VIA S.S 291','VIA ISTRIA, VIA ZARA, STRADA S.S. 127/BIS Km 4, Via Strada Statale 127bis - Porto Conte','VIA SENZA NOME 086');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (300,'90003001033','VIA SENZA NOME 057 (GIA'' STRADA VICINALE ZIRRA IN SASSARI)','VIA S.S 291','VIA OZIERI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (301,'90003001035','VIA SENZA NOME 059','STRADA PROVINCIALE 55 BIS, VIA SENZA NOME 050','VIA SENZA NOME 060, VIA SENZA NOME 062');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (302,'90003001036','VIA SENZA NOME 060','VIA SENZA NOME 059, VIA SENZA NOME 264','VIA SENZA NOME 062');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (303,'90003001037','VIA SENZA NOME 061','STRADA PROVINCIALE 55 BIS','VIA SENZA NOME 069');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (304,'90003001038','VIA SENZA NOME 062','VIA S.S 291','STRADA PROVINCIALE 55 BIS, VIA SENZA NOME 060');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (305,'90003001039','VIA SENZA NOME 063','VIA SENZA NOME 062','STRADA PROVINCIALE 55 BIS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (306,'90003001040','VIA SENZA NOME 064','VIA SENZA NOME 062','LARGO SENZA NOME 263');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (307,'90003001041','VIA SENZA NOME 065','','VIA SENZA NOME 063');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (308,'90003001042','VIA SENZA NOME 066','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (309,'90003001043','VIA SENZA NOME 067','STRADA PROVINCIALE 55 BIS','VIA SENZA NOME 062');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (310,'90003001044','VIA SENZA NOME 068','VIA SENZA NOME 067','VIA SENZA NOME 062, VIA SENZA NOME 069');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (311,'90003001045','VIA SENZA NOME 069','STRADA PROVINCIALE 55 BIS, VIA SENZA NOME 061','VIA SENZA NOME 068');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (312,'90003001046','VIA SENZA NOME 070','STRADA PROVINCIALE 55 BIS, VIA SENZA NOME 068','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (313,'90003001047','VIA SENZA NOME 071','','VIA S.S 291, VIA SENZA NOME 250');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (314,'90003001048','VIA SENZA NOME 072','VIA S.S 291','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (315,'90003001049','VIA SENZA NOME 073','VIA SENZA NOME 072','VIA SENZA NOME 075');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (316,'90003001050','VIA SENZA NOME 074','VIA S.S 291','VIA SENZA NOME 076');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (317,'90003001051','VIA SENZA NOME 075','','VIA SENZA NOME 073');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (318,'90003001052','VIA SENZA NOME 076','VIA S.S 291','VIA SENZA NOME 074');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (429,'90003001236','VIA SENZA NOME 210','VIA VITTORIO EMANUELE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (1,'90003000483','VICOLO ADAMI','VIA CARLO ALBERTO, VIA MINERVA','VIA BARCELONETTA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (2,'90003000484','VIA AGGIUS','VIA IGLESIAS, VIA LA MADDALENA','VIA PORTO TORRES');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (3,'90003000485','VIA ALES','VIA F.LLI CERVI, VIA LIDO','VIALE EUROPA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (4,'90003000486','VIA AMALFI','VIA NAPOLI','VIA PISA, VIA VENEZIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (5,'90003000487','VIA AMSICORA','VIA AMSICORA TRAV. A, VIA GARIBALDI GIUSEPPE','VIA ASFODELO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (6,'90003000488','VIA AMSICORA TRAV. A','','VIA AMSICORA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (7,'90003000489','VIA ANDREONI ANTONIO','VIA CRAVELLET, VIA SATTA SEBASTIANO','VIA DA VINCI LEONARDO, VIA BARRACU MASSIMILIANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (8,'90003000491','VIA ANGIOY G. M.','VIA GARIBALDI GIUSEPPE','VIA DEGLI ORTI, VIA PAOLI PASQUALE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (9,'90003000494','VIA ARCHIMBAO GABRIEL','VIA EINAUDI LUIGI, VIA FRANK G.','VIA DALERCI ANTONIO, VIA DE GASPERI ALCIDE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (10,'90003000495','VIA ARDUINO RAFFAELE','VIA ROMA, VICOLO DEL TEATRO','VIA DELLA MISERICORDIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (11,'90003000496','VIA ASFODELO','VIA CATALOGNA VIC.A','VIA AMSICORA, VIA JOSTO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (12,'90003000498','VIA AZUNI','VIA DEGLI ORTI','VIA DON MINZONI, VIA PAOLI PASQUALE, VIA SENZA NOME 181');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (13,'90003000499','VIA DELLE BALEARI','VIA DON MINZONI, VIALE SARDEGNA, VIA VENEZIA','VIALE EUROPA, VIA LIDO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (14,'90003000500','LARGO BALLERO AGOSTINO','VIA DELEDDA GRAZIA, VIA MARCONI GUGLIELMO','PIAZZA SENZA NOME 195');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (19,'90003000502','VIA BANYOLAS','VIA PERPIGNAN, LUNGOMARE VALENCIA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (20,'90003000503','VIA BARBAGIA','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (18,'90003001019','VIA BANCHINA SANITA''','','VIA BANCHINA DOGANA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (15,'90003001020','VIA BANCHINA DOGANA','VIA GARIBALDI GIUSEPPE, BASTIONI MADDALENA, VIA SENZA NOME 084 (SCALO TARANTIELLO), VIA BANCHINA GARIBALDI','VIA PORTA A MARE, VIA BANCHINA SANITA''');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (16,'90003001021','VIA BANCHINA GARIBALDI','','VIA GARIBALDI GIUSEPPE, VIA SENZA NOME 084 (SCALO TARANTIELLO), VIA BANCHINA DOGANA, VIA BANCHINA MILLELIRE AMMIRAGLIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (17,'90003001022','VIA BANCHINA MILLELIRE AMMIRAGLIO','VIA GARIBALDI GIUSEPPE, VIA BANCHINA GARIBALDI','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (496,'90003000999','VIA STRADA PROVINCIALE N� 55','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (430,'90003001237','VIA SENZA NOME 211','VIA S.S. 127 BIS (VIALE MEDITERRANEO)','STRADA CONSORTILE CARRABUFFAS');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (431,'90003001239','VIA SENZA NOME 213','VIA SENZA NOME 214','VIA SENZA NOME 216');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (432,'90003001240','VIA SENZA NOME 214','VIA SENZA NOME 213, VIA SENZA NOME 215','VIA SENZA NOME 217');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (433,'90003001241','VIA SENZA NOME 215','VIA SENZA NOME 214','VIA SENZA NOME 216');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (434,'90003001242','VIA SENZA NOME 216','VIA SENZA NOME 213, VIA SENZA NOME 215','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (435,'90003001243','VIA SENZA NOME 217','','VIA SENZA NOME 214');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (266,'90003000976','VIA SENZA NOME 017 (DELL''ELICRISO)','VIA SENZA NOME 031 (DELLE PALME), VIA SENZA NOME 033 (DEGLI ANEMONI)','VIA SENZA NOME 031 (DELLE PALME), VIA SENZA NOME 033 (DEGLI ANEMONI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (270,'90003000980','VIA SENZA NOME 021 (DEI CORBEZZOLI)','','VIA SENZA NOME 024 (DELLE VIGNE), VIA SENZA NOME 025 (DEGLI ULIVI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (271,'90003000981','VIA SENZA NOME 022 (DEI LECCI)','Via Senza Nome 014, VIA SENZA NOME 023 (DELLE QUERCE), VIA SENZA NOME 049 (DEGLI ULIVI (DA VIA DEGLI EUCALIPTI A VIA DEI LECCI)','Via Senza Nome 015, Via Senza Nome 016, VIA SENZA NOME 024 (DELLE VIGNE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (272,'90003000982','VIA SENZA NOME 023 (DELLE QUERCE)','','VIA SENZA NOME 022 (DEI LECCI), VIA SENZA NOME 049 (DEGLI ULIVI (DA VIA DEGLI EUCALIPTI A VIA DEI LECCI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (273,'90003000983','VIA SENZA NOME 024 (DELLE VIGNE)','VIA SENZA NOME 019 (DEI GINEPRI), VIA SENZA NOME 020 (DEI PLATANI)','Via Senza Nome 015, Via Senza Nome 016, VIA SENZA NOME 021 (DEI CORBEZZOLI), VIA SENZA NOME 022 (DEI LECCI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (274,'90003000984','VIA SENZA NOME 025 (DEGLI ULIVI)','STRADA S.S. 127/BIS Km 4, VIA SENZA NOME 020 (DEI PLATANI)','VIA SENZA NOME 024 (DELLE VIGNE), VIA SENZA NOME 031 (DELLE PALME), VIA SENZA NOME 049 (DEGLI ULIVI (DA VIA DEGLI EUCALIPTI A VIA DEI LECCI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (275,'90003000985','VIA SENZA NOME 026 (DEI PALMIZI)','STRADA S.S. 127/BIS Km 4, VIA SENZA NOME 027 (PORTO CONTE)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (276,'90003000986','VIA SENZA NOME 027 (PORTO CONTE)','STRADA S.S. 127/BIS Km 4, VIA SENZA NOME 026 (DEI PALMIZI)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (277,'90003000987','VIA SENZA NOME 028 (DEGLI OLEANDRI)','STRADA S.S. 127/BIS Km 4','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (278,'90003000988','VIA SENZA NOME 029 (DELLE GINESTRE)','VIA SENZA NOME 025 (DEGLI ULIVI)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (279,'90003000989','VIA SENZA NOME 030 (DEL MIRTO)','VIA SENZA NOME 031 (DELLE PALME)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (280,'90003000990','VIA SENZA NOME 031 (DELLE PALME)','VIA SENZA NOME 030 (DEL MIRTO)','VIA SENZA NOME 018 (TAMERICI), VIA SENZA NOME 025 (DEGLI ULIVI), VIA SENZA NOME 049 (DEGLI ULIVI (DA VIA DEGLI EUCALIPTI A VIA DEI LECCI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (281,'90003000992','VIA SENZA NOME 033 (DEGLI ANEMONI)','VIA SENZA NOME 018 (TAMERICI)','VIA SENZA NOME 017 (DELL''ELICRISO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (293,'90003001008','VIA SENZA NOME 049 (DEGLI ULIVI (DA VIA DEGLI EUCALIPTI A VIA DEI LECCI)','VIA SENZA NOME 023 (DELLE QUERCE), VIA SENZA NOME 025 (DEGLI ULIVI), VIA SENZA NOME 031 (DELLE PALME)','Via Senza Nome 014, VIA SENZA NOME 022 (DEI LECCI)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (226,'90003001023','STRADA PROVINCIALE 55 BIS','VIA ZIRRA, VIA S.S 291','VIA STRADA STATALE 127BIS - PORTO CONTE, VIA STRADA PROVINCIALE N° 55, VIA SENZA NOME 053');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (519,'90003001267','STRADA VICINALE LAS COVAS','','STRADA CONSORTILE S. ANNA POLLINA, STRADA VICINALE MAXINETTA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (520,'90003001268','STRADA VICINALE MAXINETTA','STRADA CONSORTILE S. ANNA POLLINA, STRADA VICINALE LAS COVAS','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (504,'90003000710','VIA TIZIANO','VIA DON MINZONI, VIA VILLANOVA, VIA SENZA NOME 185 (LUIGI NONO)','VIA NAPOLI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (505,'90003000711','VIA TODA EDUARD','VIA F.LLI CANELLES','VIA F.LLI KENNEDY');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (506,'90003000712','VIA TOGLIATTI PALMIRO','VIA GIOLITTI GIOVANNI, VIA STURZO DON LUIGI','VIA DE GASPERI ALCIDE, VIA F.LLI ROSSELLI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (507,'90003000713','VIA TORRICELLI','','VIA PACINOTTI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (508,'90003000714','VIA TORRICELLI TRAV. A','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (509,'90003000715','VIA TOSCANA','VIA LIGURIA, STRADA SENZA NOME 175','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (511,'90003000717','VIA TXU TERRAT','VIA F.LLI KENNEDY, VIA TODA EDUARD','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (512,'90003000719','LUNGOMARE VALENCIA','VIA BANYOLAS, LUNGOMARE DANTE','VIALE DELLA RESISTENZA, PIAZZALE EL TRO'' (VIA JOSE'' MARIA ESCRIVA), VIA SENZA NOME 242 (COMUNEMENTE NOTO P. BALAGUER)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (513,'90003000720','VIA VALVERDE','VIA CARRABUFFAS, VIA GIOLITTI GIOVANNI, VIA SANT''AGOSTINO','VIA VALVERDE I STRADA, STRADA SENZA NOME 231');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (515,'90003000722','VIA VANONI EZIO','','VIA EINAUDI LUIGI, VIA MATTEI ENRICO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (516,'90003000723','VIA VENEZIA','VIA DELLE BALEARI, VIA DON MINZONI, VIA VILLANOVA','VIA NAPOLI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (531,'90003000725','VIALE XXIV MAGGIO','VIA GARIBALDI GIUSEPPE, VIA DEGLI ORTI','VIA ASFODELO, VIA CATALOGNA, VIA DIEZ SALVATORE, VIA VITTORIO VENETO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (532,'90003000726','VIA XX SETTEMBRE','VIA F.LLI KENNEDY, VIA SASSARI, PIAZZA SULIS','VIA SENZA NOME 198');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (518,'90003000727','VIA VERDI GIUSEPPE','VIA SANT''AGOSTINO','VIA ROTH ANGELO, VIA TARRAGONA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (521,'90003000728','VIA VILLAFRANCA DEL PANADES','VIA COROS, VIA SANT''ANNA','VIA CARBIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (522,'90003000729','VIA VILLANOVA','','VIA TIZIANO, VIA VENEZIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (523,'90003000730','PIAZZA VITTORIO EMANUELE','','VIA ARDUINO RAFFAELE, VIA PRINCIPE UMBERTO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (524,'90003000731','VIA VITTORIO EMANUELE','VIA CAGLIARI, VIA SASSARI','VIA SENZA NOME 209 (VIA MOSSA ANTONI SIMON), VIA SENZA NOME 210, VIA S.S. 127 BIS (VIALE MEDITERRANEO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (525,'90003000732','VIA VITTORIO EMANUELE TRAV. A','','VIA VITTORIO EMANUELE TRAV. B, VIA VITTORIO VENETO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (526,'90003000733','VIA VITTORIO EMANUELE TRAV. B','VIA VITTORIO EMANUELE','VIA VITTORIO EMANUELE TRAV. A');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (527,'90003000734','VIA VITTORIO VENETO','VIA CATALOGNA, VIA DIEZ SALVATORE, VIALE XXIV MAGGIO, VIA VITTORIO EMANUELE TRAV. A','VIA DELEDDA GRAZIA, VIA SANT''AGOSTINO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (528,'90003000735','VIA VIVALDI ANTONIO','VIALE GIOVANNI XXIII, VIA PAGANINI','VIA VIVALDI ANTONIO TRAV. A');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (529,'90003000736','VIA VIVALDI ANTONIO TRAV. A','','VIA VIVALDI ANTONIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (530,'90003000737','VIA VOLTA ALESSANDRO','','VIA DEGLI ORTI, VIA PACINOTTI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (533,'90003000738','VIA ZACCARIA','VIA DELLA MISERICORDIA','VIA LACCU SIMON');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (517,'90003000750','PIAZZA VENEZIA GIULIA','VIA ISTRIA','VIA ORSERA, VIA PARENZO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (534,'90003000751','VIA ZARA','VIA ISTRIA, VIA PARENZO, STRADA S.S. 127/BIS Km 4, Via Strada Statale 127bis - Porto Conte, VIA S.S 291','LUNGOMARE ROVIGNO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (535,'90003000756','VIA ZIRRA','STRADA PROVINCIALE 55 BIS, VIA S.S 291','PIAZZA OLBIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (514,'90003000869','VIA VALVERDE I STRADA','VIA DE MURO TRAV. A, VIA VALVERDE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (510,'90003000939','Via Trieste','','VIA FIUME, LUNGOMARE ROVIGNO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (60,'90003001086','STRADA CONSORTILE LA RUCCHETTA','STRADA S.S.VAR. CALICH, STRADA SENZA NOME 103, STRADA SENZA NOME 106','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (59,'90003001101','STRADA CONSORTILE LA RUCCHETTA','STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 112, STRADA SENZA NOME 150, STRADA SENZA NOME 153','STRADA SENZA NOME 106');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (66,'90003001111','STRADA CONSORTILE SAN QUIRICO','STRADA STRADA PROVINCIALE 42, STRADA SENZA NOME 122, STRADA SENZA NOME 137','STRADA SENZA NOME 112, STRADA SENZA NOME 118');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (57,'90003001114','STRADA CONSORTILE FIGURUJA','STRADA SENZA NOME 120, STRADA SENZA NOME 128','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (56,'90003001121','STRADA CONSORTILE FIGURUJA','','STRADA SENZA NOME 132');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (62,'90003001142','STRADA CONSORTILE PONEDDU PUNTET','STRADA CONSORTILE UNGIAS','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (23,'90003001214','VIA BARRACU MASSIMILIANO','VIA CARRABUFFAS, VIA PIERINO ENRICO','VIA MARCONI GUGLIELMO, VIA XX SETTEMBRE, VIA SENZA NOME 190');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (55,'90003001226','STRADA CONSORTILE CARRABUFFAS','VIA CARRABUFFAS, VIA SENZA NOME 211','VIA S.S. 127 BIS (VIALE MEDITERRANEO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (67,'90003001227','STRADA CONSORTILE SCALA MALA','VIA S.S. 127 BIS (VIALE MEDITERRANEO)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (61,'90003001251','STRADA CONSORTILE MONTAGNESE','VIA DEGLI ORTI, VIA DEGLI ORTI TRAV. B','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (398,'90003001193','STRADA SENZA NOME 170','','STRADA SENZA NOME 169');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (399,'90003001194','STRADA SENZA NOME 171','VIALE I MAGGIO','VIALE EUROPA, STRADA SENZA NOME 169');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (400,'90003001195','STRADA SENZA NOME 172','VIALE I MAGGIO, STRADA SENZA NOME 169','VIALE I MAGGIO, STRADA SENZA NOME 169');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (401,'90003001196','STRADA SENZA NOME 173','VIALE I MAGGIO, STRADA SENZA NOME 169','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (402,'90003001198','STRADA SENZA NOME 175','VIA CALABRIA, VIALE EUROPA','VIA TOSCANA, STRADA SENZA NOME 169, STRADA SENZA NOME 179');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (403,'90003001202','STRADA SENZA NOME 179','STRADA SENZA NOME 169','VIA LIGURIA, STRADA SENZA NOME 175');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (404,'90003001204','VIA SENZA NOME 181','VIA AZUNI, VIA DON MINZONI','VIA DE GIORGIO GIOVANNI, VIA LA MADDALENA, VIA PORTO TORRES');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (405,'90003001205','VIA SENZA NOME 182 (PABLO PICASSO)','VIA FLEMING, VIA SENZA NOME 184 (JUAN MIRÒ)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (406,'90003001206','VIA SENZA NOME 183 (ANTONI GAUD�)','VIA DON MINZONI, VIA SENZA NOME 184 (JUAN MIRÒ)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (407,'90003001207','VIA SENZA NOME 184 (JUAN MIR�)','VIA FLEMING, VIA SENZA NOME 182 (PABLO PICASSO)','VIA DON MINZONI TRAV. A, VIA SENZA NOME 183 (ANTONI GAUDÌ)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (408,'90003001208','VIA SENZA NOME 185 (LUIGI NONO)','','VIA DON MINZONI, VIA FLEMING, VIA TIZIANO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (409,'90003001209','VIA SENZA NOME 186 (SALVADOR ESPRIU)','','VIA FLEMING');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (410,'90003001210','VIA SENZA NOME 187 (SALVADOR DAL�)','','VIA DON MINZONI TRAV. A');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (411,'90003001211','VIA SENZA NOME 188','','VIA F.LLI CERVI, VIA LIDO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (412,'90003001212','VIA SENZA NOME 189','','VIA DON MINZONI');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (413,'90003001213','VIA SENZA NOME 190','VIA XX SETTEMBRE, VIA BARRACU MASSIMILIANO','VIA JOSTO, VIA VITTORIO EMANUELE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (414,'90003001215','VIA SENZA NOME 191','','VIA MAZZINI GIUSEPPE, VIA XX SETTEMBRE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (415,'90003001218','VIA SENZA NOME 194','VIA MAZZINI GIUSEPPE, VIA XX SETTEMBRE','VIA VITTORIO EMANUELE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (416,'90003001219','PIAZZA SENZA NOME 195','LARGO BALLERO AGOSTINO, LARGO COSTANTINO NUNZIO','LARGO BALLERO AGOSTINO, LARGO COSTANTINO NUNZIO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (417,'90003001221','VIA SENZA NOME 197','VIA CARRABUFFAS, VIA MONT D''OLLA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (418,'90003001222','VIA SENZA NOME 198','VIA MAZZINI GIUSEPPE, VIA XX SETTEMBRE','VIA MAZZINI GIUSEPPE, VIA XX SETTEMBRE');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (419,'90003001224','VIA SENZA NOME 200','STRADA CONSORTILE UNGIAS','VIA SENZA NOME 265');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (420,'90003001225','VIA SENZA NOME 201','VIA S.S. 127 BIS (VIALE MEDITERRANEO)','VIA SENZA NOME 265');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (421,'90003001228','VIA SENZA NOME 202','VIA SENZA NOME 203, VIA SENZA NOME 205','VIA S.S. 127 BIS (VIALE MEDITERRANEO)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (436,'90003001244','VIA SENZA NOME 218','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (437,'90003001245','VIA SENZA NOME 219','','VIA S.S. 127 BIS (VIALE MEDITERRANEO), VIA SENZA NOME 221 (IL CARMINE), VIA SENZA NOME 222 (SANTA CHIARA)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (438,'90003001246','VIA SENZA NOME 220','VIA S.S. 127 BIS (VIALE MEDITERRANEO)','VIA SENZA NOME 229');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (486,'90003001247','VIA S.S. 127 BIS (VIALE MEDITERRANEO)','VIA SENZA NOME 209 (VIA MOSSA ANTONI SIMON), VIA VITTORIO EMANUELE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (481,'90003001248','VIA S.P. 19','VIA S.S. 127 BIS (VIALE MEDITERRANEO)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (439,'90003001249','VIA SENZA NOME 221 (IL CARMINE)','VIA SENZA NOME 219, VIA SENZA NOME 222 (SANTA CHIARA), VIA SENZA NOME 227 (VIA FEDELE CILLIANO)','VIA SENZA NOME 209 (VIA MOSSA ANTONI SIMON), VIA SENZA NOME 226 (MIQUEL CHESSA)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (440,'90003001250','VIA SENZA NOME 222 (SANTA CHIARA)','VIA SENZA NOME 219, VIA SENZA NOME 221 (IL CARMINE)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (441,'90003001252','VIA SENZA NOME 223 (RAFAEL SARI)','','VIA SENZA NOME 221 (IL CARMINE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (442,'90003001253','VIA SENZA NOME 224 (SCANU PASQUAL)','','VIA SENZA NOME 221 (IL CARMINE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (443,'90003001254','VIA SENZA NOME 225 (GIGLIO VITTORIO)','','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (444,'90003001255','VIA SENZA NOME 226 (MIQUEL CHESSA)','','VIA SENZA NOME 221 (IL CARMINE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (445,'90003001256','VIA SENZA NOME 227 (VIA FEDELE CILLIANO)','','VIA SENZA NOME 221 (IL CARMINE)');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (446,'90003001258','VIA SENZA NOME 229','','VIA SENZA NOME 220');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (447,'90003001259','VIA SENZA NOME 230','','VIA SENZA NOME 200');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (448,'90003001261','STRADA SENZA NOME 231','VIA VALVERDE','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (365,'90003001274','VIA SENZA NOME 134 (TRAVERSA VIA ELTRO'')','VIALE DELLA RESISTENZA, PIAZZALE EL TRO'' (VIA JOSE'' MARIA ESCRIVA)','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (458,'90003001283','VIA SENZA NOME 244','','VIALE GIOVANNI XXIII');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (459,'90003001281','VIA SENZA NOME 245','VIA SANT''ANNA','VIA SENZA NOME 238');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (456,'90003001289','VIA SENZA NOME 242 (COMUNEMENTE NOTO P. BALAGUER)','','PIAZZALE EL TRO'' (VIA JOSE'' MARIA ESCRIVA), LUNGOMARE VALENCIA');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (468,'90003001290','VIA SENZA NOME 253','VIA CARRABUFFAS','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (470,'90003000941','VIA SENZA NOME 255 (PIACENTINI)','VIA FIUME, VIA ORSERA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (471,'90003000942','VIA SENZA NOME 256 (TUFAROLI)','VIA ORSERA','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (472,'90003000948','VIA SENZA NOME 257 (UDINE)','','VIA FIUME, LUNGOMARE ROVIGNO');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (473,'90003000949','VIA SENZA NOME 258 (SPALATO)','VIA DALMAZIA, VIA PARENZO TRAV.A','VIA PARENZO TRAV.B');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (474,'90003001294','LARGO SENZA NOME 263','VIA SENZA NOME 064','');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (475,'90003001295','VIA SENZA NOME 264','','VIA SENZA NOME 060');
insert into public.inizio_fine_strade (id, strada_id, strada_nome, da, a) values (476,'90003001296','VIA SENZA NOME 265','VIA SENZA NOME 201','VIA SENZA NOME 200');

